lab11/Models/ErrorViewModel.cs
namespace lab_11.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab11/Models/Order.cs
namespace lab_11.Models
{
    public class Order
    {
        private static int _id = 1;
        public int OrderId { get; private set; }
        public string OrderName { get; set; }
        public int OrderPrice { get; set; }
        public DateTime CreatedAt { get; set; }
        public Order()
        {
            OrderName = "";
            OrderId = _id++;
            CreatedAt = DateTime.Now;
        }
        public override string ToString()
        {
            return $"Order Id:{OrderId} Name:{OrderName} Price:{OrderPrice} CreatedAt:{CreatedAt}";
        }
    }
}

lab11/Models/Weaher.cs
namespace lab_11.Models
{
    public class Coord
    {
        public double lon { get; set; }
        public double lat { get; set; }
        public override string ToString()
        {
            return $"lat : {lat}, lon : {lon}";
        }
    }

    public class Weather
    {
        public int id { get; set; }
        public string? main { get; set; }
        public string? description { get; set; }
        public string? icon { get; set; }
    }

    public class Main
    {
        public double temp { get; set; }
        public double? feels_like { get; set; }
        public double? temp_min { get; set; }
        public double? temp_max { get; set; }
        public int? pressure { get; set; }
        public int? humidity { get; set; }
        public int? sea_level { get; set; }
        public int? grnd_level { get; set; }
    }

    public class Wind
    {
        public double? speed { get; set; }
        public int? deg { get; set; }
        public double? gust { get; set; }
    }

    public class Clouds
    {
        public int? all { get; set; }
    }

    public class Sys
    {
        public string? country { get; set; }
        public long? sunrise { get; set; }
        public long? sunset { get; set; }
    }

    public class WeatherData
    {
        public Coord? coord { get; set; }
        public List<Weather>? weather { get; set; }
        public string? @base { get; set; }
        public Main? main { get; set; }
        public int? visibility { get; set; }
        public Wind? wind { get; set; }
        public Clouds? clouds { get; set; }
        public int? dt { get; set; }
        public Sys? sys { get; set; }
        public int timezone { get; set; }
        public int? id { get; set; }
        public string? name { get; set; }
        public int? cod { get; set; }
    }
}

lab11/ViewModels/HomeViewModels/ShowOrdersViewModel.cs
using lab_11.Models;
namespace lab_11.ViewModels.HomeViewModels
{
    public enum ShowStyles
    {
        List,
        Table,
        Row
    }
    public record class ShowOrdersViewModel(IEnumerable<Order> Orders, ShowStyles ShowStyle);
}


lab11/Controllers/HomeController.cs
using lab_11.Filters;
using lab_11.Models;
using lab_11.ViewModels.HomeViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Globalization;

namespace lab_11.Controllers
{
    [LogAction]
    [UserCount]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private static readonly List<Order> _orders = new();
        private static Coord _coord = new();
        private readonly string logFilePath = "actionLog.txt";
        private readonly string userCountFilePath = "userCount.txt";
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult ViewLogs()
        {
            try
            {
                var logs = System.IO.File.ReadAllLines(logFilePath);
                return View(logs);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to read logs file.");
                return View(Array.Empty<string>());
            }
        }

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SetCoord(string lat, string lon)
        {
            if (Double.TryParse(lat, NumberStyles.Float, CultureInfo.InvariantCulture, out double numberLat)
                && Double.TryParse(lon, NumberStyles.Float, CultureInfo.InvariantCulture, out double numberLon))
            {
                Console.WriteLine(numberLat);
                Console.WriteLine(numberLon);
                _coord.lat = numberLat;
                _coord.lon = numberLon;
            }
            else
            {
                throw new Exception();
            }
            return RedirectToAction("GetWeather");
        }
        [HttpGet]
        public ActionResult GetWeather()
        {
            Console.WriteLine(_coord);
            return View(_coord);
        }
        [HttpGet]
        public ActionResult AddOrder()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PostOrder(Order order, int amount)
        {
            _orders.Add(order);
            for (int i = 1; i < amount; i++)
            {
                Order newOrder = new();
                newOrder.OrderPrice = order.OrderPrice;
                newOrder.OrderName = order.OrderName;
                _orders.Add(newOrder);
            }
            return View("AddOrder");
        }
        public ActionResult ShowOrders(ShowStyles showStyle)
        {
            Console.WriteLine(showStyle);
            ShowOrdersViewModel showOrdesrViewModel = new(_orders, showStyle);
            return View(showOrdesrViewModel);
        }
        public ActionResult DeleteOrder(int Id, ShowStyles showStyle)
        {
            Console.WriteLine(showStyle);
            _orders.RemoveAll(x => x.OrderId == Id);
            return RedirectToAction("ShowOrders", new { showStyle });
        }
        public void LogAction(string action)
        {
            string logMessage = $"{action} - {DateTime.Now}";
            System.IO.File.AppendAllText("actionLog.txt", logMessage + Environment.NewLine);
        }

        [UserCount]
        public IActionResult UserStatistics()
        {
            return Content($"Total Unique Users: {GetUserCount()}");
        }

        private int GetUserCount()
        {
            var userCount = 0;
            if (System.IO.File.Exists(userCountFilePath))
            {
                userCount = int.Parse(System.IO.File.ReadAllText(userCountFilePath));
            }
            return userCount;
        }

        public void UpdateUserCount()
        {
            var userCount = GetUserCount();
            userCount++;
            System.IO.File.WriteAllText(userCountFilePath, userCount.ToString());
        }

    }
}

lab11/ViewComponents/TableViewComponent.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using lab_11.Models;
using System.Text;


namespace lab_11.ViewComponents
{
    public class TableViewComponent
    {
        public IViewComponentResult Invoke(IEnumerable<Order> orders)
        {
            StringBuilder sb = new();
            foreach (var order in orders)
            {
                sb.Append(order.ToString() + "<br/>");
            }

            return new HtmlContentViewComponentResult(new HtmlString(sb.ToString()));
        }

    }
}

lab11/ViewComponents/WeatherViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using lab_11.Services.WeatherService;
using lab_11.Models;

namespace lab_11.ViewComponents
{
    public class WeatherViewComponent : ViewComponent
    {
        private readonly IWeatherService _weatherService;

        public WeatherViewComponent(IWeatherService myService)
        {
            _weatherService = myService;
        }
        public async Task<IViewComponentResult> InvokeAsync(Coord coord)
        {
            WeatherData weather = await _weatherService.GetWeatherAsync(coord.lat, coord.lon);
            return View(weather);
        }

    }
}

lab11/Views/Home/AddOrder.cshtml
@model Order 

<form asp-action="PostOrder" method="post">
    <div class="form-group">
        <label asp-for="OrderName">Name</label>
        <input asp-for="OrderName" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="OrderPrice">Price ($)</label>
        <input asp-for="OrderPrice" class="form-control" required />
    </div>
    <div class="form-group">
        <label>Amount</label>
        <input min="1" type="number" value="1" name="amount" class="form-control" required />
    </div>
    <button style="width:100%;margin-top: 15px" type="submit" class="btn btn-primary btn-block">Create Order</button>
</form>

lab11/Views/Home/GetWeather.cshtml
@model Coord
@{
    var weather = await Component.InvokeAsync("Weather", Model);
}
<div class="container mt-4">
    @weather
    <form method="post" asp-action="SetCoord">
        <div class="form-group">
            <label asp-for="lat">Latitude:</label>
            <input asp-for="lat" type="number" class="form-control" id="lat" name="lat" min="-90" max="90" step="any" placeholder="Enter latitude" value="@Model.lat" required>
        </div>
        <div class="form-group">
            <label asp-for="lon">Longitude:</label>
            <input asp-for="lon" type="number" class="form-control" id="lon" name="lon" min="-180" max="180" step="any" placeholder="Enter longitude" value="@Model.lon" required>
        </div>
        <button style ="width:100%;margin-top: 15px" type="submit" class="btn btn-primary" id="confirmButton">Confirm</button>
    </form>
</div>

lab11/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p><a asp-action="ViewLogs" asp-controller="Home">View Logs</a>.</p>
</div>

lab11/Views/Home/ShowOrders.cshtml
@using lab_11.ViewModels.HomeViewModels
@model ShowOrdersViewModel
<div class="container">
    <h1>Products</h1>

    <form action="ShowOrders">
        <div class="form-group">
            <label for="viewSelect">View:</label>
            <select asp-for=ShowStyle class="form-control" id="viewSelect">
                <option value="@ShowStyles.List">List View</option>
                <option value="@ShowStyles.Table">Table View</option>
                <option value="@ShowStyles.Row">Row View</option>
            </select>

        </div>
        <button style="width:100%;margin-top: 15px" type="submit" class="btn btn-primary btn-block">Change view</button>
    </form>
    @if (Model.ShowStyle == ShowStyles.Row)
    {
        @await Component.InvokeAsync("Table",Model.Orders)
    }
    @if (Model.ShowStyle == ShowStyles.List)
    {
        <div id="productsList" class="list-view">
            <ul class="list-group">
                @foreach (var product in Model.Orders)
                {
                    <form method="post" action="DeleteOrder">
                    <input type="hidden" name="showStyle" value="@Model.ShowStyle" />
                    <input type="hidden" name="Id" value="@product.OrderId" />
                    <li class="list-group-item">
                            @product.OrderId. @product.OrderName - @product.OrderPrice$ (@product.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")) 
                            <button style="background:red" type="submit" class="btn btn-primary btn-block">X</button>
                    </li>
                    </form>
                }
            </ul>
        </div>
    }
    @if (Model.ShowStyle == ShowStyles.Table)
    {
    <div id="productsTable" class="table-view">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Created At</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model.Orders)
                {
                    <form action="DeleteOrder">
                            <input type="hidden" name="showStyle" value="@Model.ShowStyle" />
                            <input type="hidden" name="Id" value="@product.OrderId" />
                    <tr>
                            <th>@product.OrderId</th>
                            <th>@product.OrderName</th>
                            <th>@product.OrderPrice$</th>
                            <th>@product.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")</th>
                            <th>
                                <button style="background:red" type="submit" class="btn btn-primary btn-block">X</button>
                            </th>
                    </tr>
                    </form>
                }
            </tbody>
        </table>
    </div>
    }
</div>

lab11/Views/Home/ViewLogs.cshtml
@model string[]

@{
    ViewData["Title"] = "View Logs";
}

<h1>@ViewData["Title"]</h1>

<ul>
    @foreach (var log in Model)
    {
        <li>@log</li>
    }
</ul>

lab11/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab11</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lab9.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab11</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AddOrder">Add order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowOrders">Show orders list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetWeather">Weather</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - lab11 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>